services:
  backend:
    build:
      context: ./backend
    container_name: securebank-backend
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build:
      context: ./frontend
    container_name: securebank-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
